### ISSUE TITLE
use SettingsDefinition instead of Setting[_] ?

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-nocomma#3]
- https://github.com/sbt/sbt/blob/v1.1.1/internal/util-collection/src/main/scala/sbt/internal/util/Settings.scala#L585
- https://github.com/sbt/sbt/blob/v1.1.1/sbt/src/main/scala/Import.scala#L13
- https://github.com/sbt/sbt/blob/v1.1.1/main/src/main/scala/sbt/Project.scala#L220

`sbt.Project#settings` parameter type is `SettingsDefinition`, not `Setting[_]`. but sbt-nocomma use `Setting[_]`.
Is there any problems if use `SettingsDefinition` (type inference?) 

https://github.com/sbt/sbt-nocomma/blob/ed4fd3cc5c76486db988c595eda4a44e2fdd17c0/src/main/scala/NoCommaPlugin.scala#L9

**Comment by dwijnand** [comment]
there's no type inference reason not to use `SettingsDefinition`, to my knowledge.

**Comment by xuwei-k** [comment]
WIP https://github.com/sbt/sbt-nocomma/commit/ccdb58b11347d477cd3d9687f107314045ccc28a

almost works but There is a problem 😕 


```scala
val p = Project("foo", file(".")).settings(nocomma {
  name := "something"
  organization in ThisBuild := "com.example"
})
```

```
/sbt/sbt-nocomma/src/test/scala/NoCommaTest.scala:24:39: overloaded method value settings with alternatives:
[error]   (ss: sbt.Def.SettingsDefinition*)sbt.Project <and>
[error]   => Seq[sbt.Def.Setting[_]]
[error]  cannot be applied to (Vector[sbt.SettingsDefinition])
[error]     val p = Project("foo", file(".")).settings(nocomma {
[error]                                       ^
```


```diff
val p = Project("foo", file(".")).settings(nocomma {
  name := "something"
  organization in ThisBuild := "com.example"
+ }: _*) // works if add : _*
- })
```

Should we add following implicit class or something? 🤔 

```scala
implicit class ProjectOps(p: Project) {
  def nocommaSettings(settings: SettingsDefinition*): Project = /* macro implementation */
}
```

**Comment by xuwei-k** [comment]
> There is a problem 😕

I found a solution 😃  https://github.com/sbt/sbt-nocomma/pull/4
